### PR TITLE
Adds necessary resources for cognoma to send emails and write to s3.

### PR DESCRIPTION
**Pull request by kurtwheeler**
Addresses issues #5, #6, #7. Creates a new IAM user for cognoma servers, grants access to write S3, grants everyone access to read from those S3 buckets, and grants the user the power to send emails.

### CODE REVIEW

**Review by dcgoss — CHANGES_REQUESTED** [review]
Everything server side is working. Still cannot access a file link, such as https://cognoma-files.s3.amazonaws.com/media/notebooks/classifier_5.ipynb

**Comment by kurtwheeler** [comment]
@dcgoss and I discovered that somehow the URL got mixed up and it is in fact working with this configuration.

**Review by dhimmel — COMMENTED** [review]
concept acknowledgement. I.e. "Agree with the idea and overall direction, but haven't reviewed the code changes or tested them."

**Review by dcgoss — APPROVED** [review]

**Comment by dcgoss** [comment]
LGTM 👍

**Pull request merged**
